dist: xenial
language: ruby
rvm:
- 2.5.5
cache:
  bundler: true
addons:
  postgresql: '10'
  apt:
    packages:
    - libarchive-dev
script: bundle exec manageiq-cross_repo
matrix:
  fast_finish: true
env:
  global:
  - REPOS=jrafanie/manageiq@move_report_formatter_charting_to_core
  matrix:
  - TEST_REPO=jrafanie/manageiq@move_report_formatter_charting_to_core
  - TEST_REPO=jrafanie/manageiq-ui-classic@move_report_formatter_charting_to_core_without_deprecation_fixes
