dist: xenial
language: ruby
rvm:
- 2.5.7
cache:
  bundler: true
addons:
  postgresql: '10'
script: bundle exec manageiq-cross_repo
matrix:
  fast_finish: true
env:
  global:
  - GEM_REPOS=azure-armrest#386
  - CORE_REPO=jrafanie/manageiq@upgrade_memoist
  matrix:
  - TEST_REPO=jrafanie/manageiq@upgrade_memoist
  - TEST_REPO=manageiq-api
  - TEST_REPO=manageiq-ui-classic
  - TEST_REPO=manageiq-consumption
  - TEST_REPO=manageiq-content
  - TEST_REPO=manageiq-decorators
  - TEST_REPO=manageiq-graphql
  - TEST_REPO=manageiq-providers-amazon
  - TEST_REPO=manageiq-providers-azure
  - TEST_REPO=manageiq-providers-foreman
  - TEST_REPO=manageiq-providers-google
  - TEST_REPO=manageiq-providers-kubernetes
  - TEST_REPO=manageiq-providers-kubevirt
  - TEST_REPO=manageiq-providers-lenovo
  - TEST_REPO=manageiq-providers-nuage
  - TEST_REPO=manageiq-providers-openshift
  - TEST_REPO=manageiq-providers-openstack
  - TEST_REPO=manageiq-providers-ovirt
  - TEST_REPO=manageiq-providers-redfish
  - TEST_REPO=manageiq-providers-scvmm
  - TEST_REPO=manageiq-providers-vmware
  - TEST_REPO=manageiq-v2v
