dist: xenial
language: ruby
rvm:
- 2.5.5
cache:
  bundler: true
addons:
  postgresql: '10'
  apt:
    packages:
    - libarchive-dev
script: bundle exec manageiq-cross_repo
matrix:
  fast_finish: true
env:
  global:
  - REPOS=jrafanie/manageiq@rails-5-2_47a6b56ab_before_only_add
  matrix:
  - TEST_REPO=jrafanie/manageiq@rails-5-2_47a6b56ab_before_only_add
  - TEST_REPO=manageiq-api
  - TEST_REPO=manageiq-ui-classic
  - TEST_REPO=manageiq-automation_engine
  - TEST_REPO=manageiq-providers-vmware
